import type { Run } from './collect.js'
import type { RoundTripResult } from './types.js'

interface Tally {
  clean: number
  lossy: number
  failed: number
  rewrote: number
  total: number
}

function tally(results: RoundTripResult[]): Tally {
  const clean = results.filter((result) => result.ok).length
  const failed = results.filter((result) => result.error !== undefined).length
  const rewrote = results.filter(
    (result) => result.error === undefined && result.partsChanged.length > 0,
  ).length
  return { clean, failed, lossy: results.length - clean - failed, rewrote, total: results.length }
}

function featureDamage(results: RoundTripResult[]): Array<[string, number]> {
  const counts = new Map<string, number>()
  for (const result of results) {
    for (const loss of result.featureLoss) {
      counts.set(loss.feature, (counts.get(loss.feature) ?? 0) + 1)
    }
  }
  return [...counts].sort((a, b) => b[1] - a[1])
}

/**
 * Render the harness runs as a committed comparison. Everything here is derived
 * from the measured results, so the document cannot drift from what the harness
 * would print — regenerate with `npm run harness:doc` and the numbers move only
 * when the measurement does.
 */
export function buildComparison(runs: Run[]): string {
  const total = runs[0]?.results.length ?? 0
  const lines: string[] = []

  lines.push('# Round-trip fidelity')
  lines.push('')
  lines.push(
    `Read a real \`.xlsx\`, write it back, and check that nothing was lost. Measured over ` +
      `${total} files — ordinary workbooks plus ones carrying charts, pivot tables, drawings, ` +
      `macros and defined names — against a pinned version of the incumbent. Generated by ` +
      '`npm run harness:doc`; do not edit by hand.',
  )
  lines.push('')

  lines.push('## Results')
  lines.push('')
  lines.push('| Library | Clean | Lossy | Failed | Rewrote |')
  lines.push('| --- | --: | --: | --: | --: |')
  for (const run of runs) {
    const count = tally(run.results)
    lines.push(
      `| ${run.title} | ${count.clean} | ${count.lossy} | ${count.failed} | ${count.rewrote} |`,
    )
  }
  lines.push('')
  lines.push(
    '- **Clean** — every part and every cell value survived. **Lossy** — at least one part or ' +
      'value was dropped or altered. **Failed** — the library threw instead of producing a file.',
  )
  lines.push(
    '- **Rewrote** — files where a part that was never touched came back with different bytes. ' +
      'A clean file can still be rewritten: it means the library reserialised parts it did not ' +
      'need to, which is where an unmodelled detail quietly goes missing.',
  )
  lines.push('')

  const damaged = runs.filter((run) => featureDamage(run.results).length > 0)
  if (damaged.length > 0) {
    lines.push('## Where the loss falls')
    lines.push('')
    for (const run of damaged) {
      lines.push(`**${run.title}**`)
      lines.push('')
      lines.push('| Feature | Files damaged |')
      lines.push('| --- | --: |')
      for (const [feature, count] of featureDamage(run.results)) {
        lines.push(`| ${feature} | ${count} |`)
      }
      lines.push('')
    }
  }

  lines.push('## Method')
  lines.push('')
  lines.push(
    '- Each library reads the file and writes it back through its own API. The output is ' +
      'unzipped and compared to the input part by part, and every cell value is compared after ' +
      'a second read, so a value that survives the file but decodes differently still counts as ' +
      'a loss.',
  )
  lines.push(
    '- Parts that legitimately differ on every write are excluded: document timestamps ' +
      '(`docProps/core.xml`, `docProps/app.xml`) and the calculation chain, which a spreadsheet ' +
      'rebuilds anyway.',
  )
  lines.push(
    '- Formatting is compared per cell, by the style each cell resolves to, not by counting ' +
      'entries in the style registry — deduping or pruning an unused format is not a loss.',
  )
  lines.push(
    '- The "after editing" pass adds cells, a merge, a validation, a conditional format, a ' +
      'column width, a hyperlink and a print area, all on fresh space, and asks the same ' +
      'question — so a write path that rebuilds a container and drops what the file already held ' +
      'shows up.',
  )
  lines.push('')

  lines.push('## Reproduce')
  lines.push('')
  lines.push('```')
  lines.push('npm run fixtures:real   # fetch the corpus')
  lines.push('npm run harness         # the full per-file report')
  lines.push('npm run harness:doc     # regenerate this file')
  lines.push('```')
  lines.push('')

  return `${lines.join('\n')}\n`
}
